In [3]:
import tensorflow as tf

In [1]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [4]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])

In [5]:
nb_classes = 3 # label 수

In [6]:
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [21]:
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)

In [9]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [42]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(4001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 400 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
    
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9],
                                              [1, 3, 4, 3],
                                              [1, 1, 0, 1],
                                              [1, 0, 1, 1],
                                              [1, 10, 8, 3]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 5.61174
400 0.442935
800 0.298746
1200 0.212684
1600 0.178873
2000 0.154081
2400 0.135164
2800 0.120279
3200 0.108278
3600 0.0984059
4000 0.0901493
[[  3.19108221e-04   9.99679565e-01   1.25209476e-06]
 [  9.44782853e-01   4.97567952e-02   5.46033587e-03]
 [  1.67141110e-11   2.84592297e-05   9.99971509e-01]
 [  1.19648132e-06   1.08249532e-03   9.98916268e-01]
 [  1.00000000e+00   1.07249166e-11   8.24321368e-15]] [1 0 2 2 0]
