In [ ]:
'''read with numpy'''

In [3]:
import tensorflow as tf

In [4]:
import numpy as np

In [3]:
tf.set_random_seed(777)

In [7]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

In [5]:
xy

array([[  73.,   80.,   75.,  152.],
       [  93.,   88.,   93.,  185.],
       [  89.,   91.,   90.,  180.],
       [  96.,   98.,  100.,  196.],
       [  73.,   66.,   70.,  142.],
       [  53.,   46.,   55.,  101.]])

In [8]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [18]:
print(x_data.shape, '\n', x_data, '\n', len(x_data))
print(y_data.shape, '\n', y_data, '\n', len(y_data))

(6, 3) 
 [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]] 
 6
(6, 1) 
 [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]] 
 6


In [27]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [28]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [29]:
hypothesis = tf.matmul(X, W) + b

In [30]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [31]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

In [32]:
train = optimizer.minimize(cost)

In [33]:
sess = tf.Session()

In [34]:
sess.run(tf.global_variables_initializer())

In [37]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train],
    feed_dict = {X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val,
             "\nPrediction:\n", hy_val)


0 Cost:  1286.26 
Prediction:
 [[ 177.11280823]
 [ 226.39453125]
 [ 215.60505676]
 [ 240.0973053 ]
 [ 171.80133057]
 [ 136.67863464]]
10 Cost:  42.9379 
Prediction:
 [[ 144.2684021 ]
 [ 186.86256409]
 [ 176.68280029]
 [ 197.70336914]
 [ 141.6416626 ]
 [ 114.42932892]]
20 Cost:  42.6805 
Prediction:
 [[ 144.072052  ]
 [ 186.58261108]
 [ 176.43017578]
 [ 197.42160034]
 [ 141.42266846]
 [ 114.25247192]]
30 Cost:  42.4813 
Prediction:
 [[ 144.09672546]
 [ 186.56852722]
 [ 176.43939209]
 [ 197.42500305]
 [ 141.40649414]
 [ 114.22515869]]
40 Cost:  42.2833 
Prediction:
 [[ 144.12278748]
 [ 186.55625916]
 [ 176.45033264]
 [ 197.43032837]
 [ 141.39173889]
 [ 114.19892883]]
50 Cost:  42.0866 
Prediction:
 [[ 144.14878845]
 [ 186.54408264]
 [ 176.46128845]
 [ 197.43562317]
 [ 141.37705994]
 [ 114.17279816]]
60 Cost:  41.8911 
Prediction:
 [[ 144.17471313]
 [ 186.53192139]
 [ 176.47216797]
 [ 197.44091797]
 [ 141.36242676]
 [ 114.14673615]]
70 Cost:  41.697 
Prediction:
 [[ 144.20054626]
 [ 186.5

In [70]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [500, 60, 30]]}))

Your score will be  [[ 204.14134216]]
Other scores will be  [[ 221.97729492]
 [  66.79669952]]


In [ ]:
'''read with tensorflow'''

In [5]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv', 'data-02-test-score.csv'], shuffle=False, name='filename_queue')

In [6]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [7]:
record_defaults = [[0.],[0.],[0.],[0.]] #data type
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [8]:
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1],xy[-1:]], batch_size=10)

In [9]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [10]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [11]:
hypothesis = tf.matmul(X, W) + b

In [12]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [13]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

In [14]:
train = optimizer.minimize(cost)

In [15]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [16]:
coord = tf.train.Coordinator()

In [17]:
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

In [18]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val,
                 "\nPrediction:\n", hy_val)

0 Cost:  1179.44 
Prediction:
 [[ 115.61462402]
 [ 156.85253906]
 [ 145.59207153]
 [ 155.93688965]
 [ 126.13105774]
 [  90.81573486]
 [ 122.11566162]
 [ 157.59138489]
 [ 127.76655579]
 [ 148.20046997]]
10 Cost:  154.237 
Prediction:
 [[ 153.06005859]
 [ 110.67209625]
 [ 152.18322754]
 [ 192.00999451]
 [ 160.43153381]
 [ 185.00515747]
 [ 162.61831665]
 [ 110.10240936]
 [ 145.05665588]
 [ 192.18553162]]
20 Cost:  144.601 
Prediction:
 [[ 159.20458984]
 [ 183.61169434]
 [ 161.55273438]
 [ 109.30329895]
 [ 143.95005798]
 [ 190.79515076]
 [ 179.09370422]
 [ 192.43855286]
 [ 151.97636414]
 [ 109.88150787]]
30 Cost:  99.3927 
Prediction:
 [[ 145.07606506]
 [ 192.09069824]
 [ 180.39907837]
 [ 193.87213135]
 [ 152.94024658]
 [ 110.60372925]
 [ 152.1690979 ]
 [ 191.88713074]
 [ 160.45129395]
 [ 185.0161438 ]]
40 Cost:  151.464 
Prediction:
 [[ 153.15968323]
 [ 110.77427673]
 [ 152.47192383]
 [ 192.18141174]
 [ 160.79676819]
 [ 185.39790344]
 [ 162.4188385 ]
 [ 110.27132416]
 [ 145.3875885 ]
 [ 1