In [1]:
import tensorflow as tf

In [2]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]

In [3]:
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [4]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [5]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [6]:
hypothesis = tf.matmul(X, W) + b

In [7]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [8]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

In [14]:
train = optimizer.minimize(cost)

In [15]:
sess = tf.Session()

In [16]:
sess.run(tf.global_variables_initializer())

In [18]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  1.02242 
Prediction:
 [[ 152.86654663]
 [ 183.82765198]
 [ 181.51495361]
 [ 195.20643616]
 [ 141.75111389]]
10 Cost:  1.02011 
Prediction:
 [[ 152.8639679 ]
 [ 183.82939148]
 [ 181.51412964]
 [ 195.20611572]
 [ 141.75314331]]
20 Cost:  1.01782 
Prediction:
 [[ 152.86140442]
 [ 183.83111572]
 [ 181.51332092]
 [ 195.20582581]
 [ 141.75515747]]
30 Cost:  1.01553 
Prediction:
 [[ 152.8588562 ]
 [ 183.83285522]
 [ 181.51249695]
 [ 195.20553589]
 [ 141.75718689]]
40 Cost:  1.01325 
Prediction:
 [[ 152.85629272]
 [ 183.83456421]
 [ 181.51165771]
 [ 195.20523071]
 [ 141.75918579]]
50 Cost:  1.01101 
Prediction:
 [[ 152.85375977]
 [ 183.83627319]
 [ 181.51086426]
 [ 195.20491028]
 [ 141.76119995]]
60 Cost:  1.00875 
Prediction:
 [[ 152.85121155]
 [ 183.83798218]
 [ 181.51004028]
 [ 195.20463562]
 [ 141.76319885]]
70 Cost:  1.00651 
Prediction:
 [[ 152.84867859]
 [ 183.8396759 ]
 [ 181.50920105]
 [ 195.20431519]
 [ 141.7651825 ]]
80 Cost:  1.0043 
Prediction:
 [[ 152.84617615]
 [ 183.84